### ISSUE TITLE
Create Serializable class for starting a match

### ISSUE THREAD

**Issue by samann** [cireficc/pokemon-arena-android#27]

**Comment by samann** [comment]
https://github.com/google/gson/blob/master/UserGuide.md#custom-serialization-and-deserialization

**Comment by cireficc** [comment]
This was planned out to be `MatchStart` - see Slack #android pinned file _Initial Data Transfer.jpeg_.

**Comment by cireficc** [comment]
Turns out we can just send the entire `PokemonPlayer` object.
