### ISSUE TITLE
Custom Battle - Pokemon type bans

### ISSUE THREAD

**Issue by samann** [cireficc/pokemon-arena-android#41]
Add a custom match option for banning certain types in a match. Options could be something like:

``` java
enum TypeBan {
    NORMAL,
    FIRE,
    ...
}
```

Or something similar. Banned types would then be disabled in the UI.

**Comment by cireficc** [comment]
We decided not to implement this, because it doesn't really work. You have to _not_ match against a player who chose Pokemon that you banned, which doesn't really fit into the GPGS bitmask that is used for matchmaking.
