### ISSUE TITLE
BattlePhase is null when starting

### ISSUE THREAD

**Issue by samann** [cireficc/pokemon-arena-android#73]
Trying to start a battle phase or queue a command fails because the `currentBattlePhase` is not instantiated properly

**Comment by cireficc** [comment]
Fixed by commit [3f0f0248a2b1225ecebf07788b7e804891c0f9ab](https://github.com/cireficc/pokemon-arena-android/commit/3f0f0248a2b1225ecebf07788b7e804891c0f9ab).
